apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns-route53
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ddns-route53
            image: ddns-route53
            imagePullPolicy: IfNotPresent            
          restartPolicy: OnFailure